apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: letitfly.net
      http:
        paths:
          - path: /api/profiles
            pathType: Prefix
            backend:
              serviceName: profile-service
              servicePort: 3000
          - path: /api/property
            pathType: Prefix
            backend:
              serviceName: property-service
              servicePort: 3000
#          - path: /api/users/activities
#            pathType: Prefix
#            backend:
#              service:
#                name: user-activities-service
#                port:
#                  number: 3000
          - path: /api/friends
            pathType: Prefix
            backend:
              serviceName: friends-service
              servicePort: 3000
          - path: /api/paper-cranes
            pathType: Prefix
            backend:
              serviceName: paper-cranes-service
              servicePort: 3000
          - path: /api/users
            pathType: Prefix
            backend:
              serviceName: auth-service
              servicePort: 3000
          - path: /
            pathType: Prefix
            backend:
              serviceName: client-service
              servicePort: 80
