apiVersion: apps/v1
kind: Deployment
metadata:
  name: friends-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: friends
  template:
    metadata:
      labels:
        app: friends
    spec:
      containers:
        - name: friends
          image: lanyanxi/friends
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: http://nats-service:4222
            - name: NATS_CLUSTER_ID
              value: letitfly
            - name: MONGO_CONNECTION_URI
              value: "mongodb://friends-mongo-service:27017/friends"

---
apiVersion: v1
kind: Service
metadata:
  name: friends-service
spec:
  selector:
    app: friends
  ports:
    - name: friends
      protocol: TCP
      port: 3000
      targetPort: 3000
