apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-info-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-info
  template:
    metadata:
      labels:
        app: user-info
    spec:
      containers:
        - name: user-info
          image: lanyanxi/user-info
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: http://nats-service:4222
            - name: NATS_CLUSTER_ID
              value: letitfly
            - name: MONGO_CONNECTION_URI
              value: "mongodb://user-info-mongo-service:27017/user-info"

---
apiVersion: v1
kind: Service
metadata:
  name: user-info-service
spec:
  selector:
    app: user-info
  ports:
    - name: user-info
      protocol: TCP
      port: 3000
      targetPort: 3000
